//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TojasGyar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TojasGyar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE TojasGyar_Gyak - Törölni
        ///USE TojasGyar_Gyak - Törölni
        ///
        ///CREATE TABLE Nyul(
        ///Id INT PRIMARY KEY,
        ///Nev VARCHAR(30),
        ///Nem BIT);
        ///
        ///CREATE TABLE Tojas(
        ///Id INT PRIMARY KEY,
        ///Szin VARCHAR(10),
        ///Suly INT);
        ///
        ///CREATE TABLE Termeles(
        ///Id INT PRIMARY KEY IDENTITY,
        ///Datum DATE,
        ///TipusId INT FOREIGN KEY REFERENCES Tojas(Id),
        ///NyulId INT FOREIGN KEY REFERENCES Nyul(Id),
        ///Mennyiseg INT);
        ///
        ///INSERT INTO Nyul VALUES
        ///(1, &apos;Mr. Alfie McWiggles&apos;, 1),
        ///(2, &apos;Queen Lolly Palomino&apos;, 0),
        ///(3, &apos;Mistress Hoppy Chi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBCreator {
            get {
                return ResourceManager.GetString("DBCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nyul {
            get {
                object obj = ResourceManager.GetObject("nyul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] T2 {
            get {
                object obj = ResourceManager.GetObject("T2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
